name: Dart Linux Build

on:
  push:
    branches: [ main, master ]
    paths:
      - 'dart/**'  # Only trigger on changes in dart directory
  pull_request:
    branches: [ main, master ]
    paths:
      - 'dart/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dart  # Set default working directory for all run steps

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        
      - name: Install dependencies
        run: dart pub get
        
      - name: Compile executable
        run: |
          mkdir -p build
          dart compile exe bin/main.dart -o build/program
        
      - name: Upload Linux executable
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dart/build/program  # Updated path to include dart directory